// 「まちづくりと統計」書籍の表1〜3（都市計画基礎調査のデータ項目、人口・経済に関する基本統計、
// 交通/地価/自然的環境/災害/その他）を1つの配列に構造化したもの。
// UIのカテゴリツリーとダウンロード処理の両方がこの配列を単一情報源として参照する。

export type ApiProvider = "estat" | "reinfolib" | null;

export interface CatalogItem {
  id: string;
  category: string;
  subcategory?: string;
  itemName: string;
  publisher: string;
  frequency: string;
  apiProvider: ApiProvider;
  /** MVPで実際にダウンロード可能なら true。false は「データなし・情報源のみ」表示 */
  apiAvailable: boolean;
  /** e-Stat 統計表ID（政府統計コード）。確定後に埋める */
  estatStatsCode?: string;
  /** 不動産情報ライブラリ（XPT002）の地価情報区分。0=地価公示のみ, 1=都道府県地価調査のみ */
  reinfolibPriceClassification?: "0" | "1";
  sourceUrl?: string;
  note?: string;
}

export const catalog: CatalogItem[] = [
  // ── 人口 ────────────────────────────────────────────
  {
    id: "population-census",
    category: "人口",
    subcategory: "人口規模・増減・昼間人口・通勤通学移動",
    itemName: "国勢調査",
    publisher: "総務省",
    frequency: "5年ごと",
    apiProvider: "estat",
    apiAvailable: true,
    sourceUrl: "https://www.e-stat.go.jp/",
    note: "人口規模・人口増減・昼間人口・通勤通学移動・住宅の所有関係別/建て方別世帯数・産業/職業分類別就業者数の元データ",
  },
  {
    id: "vital-statistics",
    category: "人口",
    subcategory: "将来人口（出生・死亡）",
    itemName: "人口動態調査",
    publisher: "厚生労働省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
    sourceUrl: "https://www.e-stat.go.jp/",
  },
  {
    id: "resident-registry-migration",
    category: "人口",
    subcategory: "将来人口（転入・転出）",
    itemName: "住民基本台帳人口移動報告",
    publisher: "総務省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
    sourceUrl: "https://www.e-stat.go.jp/",
  },
  {
    id: "population-projection",
    category: "人口",
    subcategory: "将来推計人口・世帯数・DID",
    itemName: "日本の地域別将来推計人口",
    publisher: "国立社会保障・人口問題研究所",
    frequency: "概ね5年ごと",
    apiProvider: null,
    apiAvailable: false,
    sourceUrl: "https://www.ipss.go.jp/",
    note: "社人研サイトで都道府県・市区町村別に公表。API未整備",
  },

  // ── 産業（企業・産業関連） ──────────────────────────
  {
    id: "economic-census-basic",
    category: "産業",
    subcategory: "事業所数・従業者数",
    itemName: "経済センサス-基礎調査",
    publisher: "総務省・経済産業省",
    frequency: "5年ごと",
    apiProvider: "estat",
    apiAvailable: false,
    sourceUrl: "https://www.e-stat.go.jp/",
  },
  {
    id: "economic-census-activity",
    category: "産業",
    subcategory: "事業所数・従業者数・売上金額",
    itemName: "経済センサス-活動調査",
    publisher: "総務省・経済産業省",
    frequency: "年次*",
    apiProvider: "estat",
    apiAvailable: true,
    sourceUrl: "https://www.e-stat.go.jp/",
    note: "*経済センサス実施年は経済センサスで調査し、製造業分を集計",
  },
  {
    id: "industrial-statistics",
    category: "産業",
    subcategory: "製造業実態",
    itemName: "工業統計調査",
    publisher: "総務省・経済産業省",
    frequency: "年次*",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "economic-structure-survey",
    category: "産業",
    subcategory: "産業構造実態",
    itemName: "経済構造実態調査",
    publisher: "経済産業省",
    frequency: "年次*",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "agriculture-forestry-census",
    category: "産業",
    subcategory: "農地転用状況（行政区域全体）",
    itemName: "農林業センサス",
    publisher: "農林水産省",
    frequency: "5年ごと",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "fishery-census",
    category: "産業",
    itemName: "漁業センサス",
    publisher: "農林水産省",
    frequency: "5年ごと",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "commerce-dynamic-statistics",
    category: "産業",
    itemName: "商業動態統計調査",
    publisher: "経済産業省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "mining-industrial-index",
    category: "産業",
    itemName: "鉱工業指数",
    publisher: "経済産業省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "zoning-status",
    category: "産業",
    subcategory: "区域区分の状況",
    itemName: "区域区分の見直し資料",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "都市計画図書、区域区分の見直し資料等から収集",
  },

  // ── 家計・労働 ──────────────────────────────────────
  {
    id: "household-survey",
    category: "家計・労働",
    itemName: "家計調査",
    publisher: "総務省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "national-survey-family-income",
    category: "家計・労働",
    itemName: "消費実態調査（全国家計構造調査）",
    publisher: "総務省",
    frequency: "5年ごと",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "employment-status-survey",
    category: "家計・労働",
    itemName: "就業構造基本調査",
    publisher: "総務省",
    frequency: "5年ごと",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "wage-structure-survey",
    category: "家計・労働",
    itemName: "賃金構造基本統計調査",
    publisher: "厚生労働省",
    frequency: "年次",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "labour-force-survey",
    category: "家計・労働",
    itemName: "労働力調査",
    publisher: "総務省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: true,
    sourceUrl: "https://www.e-stat.go.jp/",
  },
  {
    id: "employment-security-statistics",
    category: "家計・労働",
    itemName: "職業安定業務統計",
    publisher: "厚生労働省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "monthly-labour-survey",
    category: "家計・労働",
    itemName: "毎月勤労統計",
    publisher: "厚生労働省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
  },

  // ── 物価・地価 ──────────────────────────────────────
  {
    id: "retail-price-survey-structure",
    category: "物価・地価",
    itemName: "小売物価統計調査（構造編）",
    publisher: "総務省",
    frequency: "年次",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "retail-price-survey-trend",
    category: "物価・地価",
    itemName: "小売物価統計調査（動向編）",
    publisher: "総務省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "consumer-price-index",
    category: "物価・地価",
    itemName: "消費者物価指数",
    publisher: "総務省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: true,
    sourceUrl: "https://www.e-stat.go.jp/",
  },
  {
    id: "cpi-regional-difference",
    category: "物価・地価",
    itemName: "消費者物価地域差指数",
    publisher: "総務省",
    frequency: "年次",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "land-price-publication",
    category: "物価・地価",
    itemName: "地価公示",
    publisher: "国土交通省",
    frequency: "半年",
    apiProvider: "reinfolib",
    apiAvailable: true,
    reinfolibPriceClassification: "0",
    sourceUrl: "https://www.reinfolib.mlit.go.jp/",
  },
  {
    id: "prefectural-land-price-survey",
    category: "物価・地価",
    itemName: "都道府県地価調査（基準地価）",
    publisher: "都道府県",
    frequency: "半年",
    apiProvider: "reinfolib",
    apiAvailable: true,
    reinfolibPriceClassification: "1",
    sourceUrl: "https://www.reinfolib.mlit.go.jp/",
  },
  {
    id: "roadside-land-price",
    category: "物価・地価",
    itemName: "路線価",
    publisher: "国税庁",
    frequency: "年次",
    apiProvider: null,
    apiAvailable: false,
    sourceUrl: "https://www.rosenka.nta.go.jp/",
    note: "国税庁の財産評価基準書（路線価図）。公式APIなし",
  },

  // ── 県民経済計算 ────────────────────────────────────
  {
    id: "prefectural-accounts",
    category: "県民経済計算",
    itemName: "県民経済計算・県内総生産・県民所得",
    publisher: "都道府県",
    frequency: "年次",
    apiProvider: null,
    apiAvailable: false,
    note: "都道府県ごとに個別公開されており統一APIなし",
  },
  {
    id: "municipal-accounts",
    category: "県民経済計算",
    itemName: "市内総生産・市民所得",
    publisher: "市",
    frequency: "年次",
    apiProvider: null,
    apiAvailable: false,
    note: "市ごとに個別公開されており統一APIなし",
  },
  {
    id: "input-output-table",
    category: "県民経済計算",
    itemName: "産業連関表・延長産業連関表",
    publisher: "市・総務省",
    frequency: "年次 / 5年ごと",
    apiProvider: "estat",
    apiAvailable: false,
  },

  // ── 土地利用 ────────────────────────────────────────
  {
    id: "land-use-status",
    category: "土地利用",
    itemName: "土地利用現況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "現地調査、空中写真、固定資産課税台帳、登記簿、住宅地図等より収集",
  },
  {
    id: "public-land-status",
    category: "土地利用",
    itemName: "国公有地の状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "登記簿、庁内資料から収集",
  },
  {
    id: "residential-development-status",
    category: "土地利用",
    itemName: "宅地開発状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "市街地開発事業等は都市計画図書等、開発許可による開発は開発登録簿から収集",
  },
  {
    id: "farmland-conversion-status",
    category: "土地利用",
    itemName: "農地転用状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "農地転用申請書から収集。面積は都市計画区域内は土地利用現況、行政区域全体は農林業センサスより収集",
  },
  {
    id: "forest-land-conversion-status",
    category: "土地利用",
    itemName: "林地転用状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "地域森林計画対象民有林は林地開発許可申請、保安林は保安林指定（解除）申請書から収集",
  },
  {
    id: "new-construction-trend",
    category: "土地利用",
    itemName: "新築動向",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "建築確認申請、登記簿（固定資産台帳）から収集",
  },
  {
    id: "ordinance-agreement-status",
    category: "土地利用",
    itemName: "条例・協定",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
  },
  {
    id: "agri-forestry-fishery-policy-status",
    category: "土地利用",
    itemName: "農林漁業関係施策適用状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
  },

  // ── 建物 ────────────────────────────────────────────
  {
    id: "building-use-status",
    category: "建物",
    itemName: "建物利用現況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "現地調査、空中写真、固定資産台帳、登記簿、建築確認申請、住宅地図等から収集",
  },
  {
    id: "large-retail-store-status",
    category: "建物",
    itemName: "大規模小売店舗等の立地状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "法律に基づく届出資料等から収集",
  },
  {
    id: "housing-tenure-type",
    category: "建物",
    itemName: "住宅の所有関係別・建て方別世帯数",
    publisher: "総務省",
    frequency: "5年ごと",
    apiProvider: "estat",
    apiAvailable: false,
    note: "国勢調査に含まれる",
  },

  // ── 都市施設 ────────────────────────────────────────
  {
    id: "urban-facility-status",
    category: "都市施設",
    itemName: "都市施設の位置・内容等",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "都市計画図書、都市計画総括図（都市施設）、庁内資料等から収集",
  },
  {
    id: "road-status",
    category: "都市施設",
    itemName: "道路の状況",
    publisher: "国・都道府県・市町村",
    frequency: "-",
    apiProvider: "reinfolib",
    apiAvailable: false,
    note: "国や都道府県、市町村の道路台帳、デジタル道路地図、ベクトルタイルデータから収集。国土数値情報の道路データは不動産情報ライブラリAPI経由で取得できる可能性あり（要検証）",
  },

  // ── 交通 ────────────────────────────────────────────
  {
    id: "traffic-volume",
    category: "交通",
    itemName: "主要な幹線の断面交通量・混雑度・旅行速度",
    publisher: "国土交通省",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "全国道路交通・街路情勢調査（一般交通量調査）報告書から収集",
  },
  {
    id: "vehicle-od-flow",
    category: "交通",
    itemName: "自動車流動量",
    publisher: "国土交通省",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "全国道路交通・街路情勢調査（自動車起終点調査）報告書から収集",
  },
  {
    id: "rail-tram-status",
    category: "交通",
    itemName: "鉄道・路面電車等の状況",
    publisher: "各交通事業者",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "各交通事業者資料、大都市交通センサス（三大都市圏のみ）、都市交通年報（三大都市圏のみ）から収集",
  },
  {
    id: "bus-status",
    category: "交通",
    itemName: "バスの状況",
    publisher: "各交通事業者",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "乗降客数は一般乗合旅客自動車運送事業輸送実績報告書から収集。GTFS-JPでオープンデータ公開している自治体はそのデータが活用可能",
  },

  // ── 自然的環境 ──────────────────────────────────────
  {
    id: "terrain-hydrology-geology",
    category: "自然的環境",
    itemName: "地形・水系・地質条件",
    publisher: "国土地理院・国土交通省",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "土地条件図・治水地形分類図（国土地理院）、主要水系調査（不動産・建設経済局）、土地分類基本調査（国土政策局）等をもとに整理",
  },
  {
    id: "weather-status",
    category: "自然的環境",
    itemName: "気象状況",
    publisher: "気象庁",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "気象庁の観測データ、大気汚染常時監視測定局の測定データ等から収集。観測地点ベースで市区町村と単純対応しないため対象外",
  },
  {
    id: "greenery-status",
    category: "自然的環境",
    itemName: "緑の状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "航空写真、衛星画像、土地利用現況調査より収集・作成",
  },
  {
    id: "flora-fauna-survey",
    category: "自然的環境",
    itemName: "動植物調査",
    publisher: "環境省・都道府県・市町村",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "自然環境保全基礎調査、河川水辺の国勢調査、環境省レッドデータブック、都道府県又は市町村による既存調査、庁内資料等から収集",
  },

  // ── 災害 ────────────────────────────────────────────
  {
    id: "disaster-occurrence-status",
    category: "災害",
    itemName: "災害の発生状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "既往災害は庁内資料、災害リスク情報は国・都道府県・市町村のハザードマップ等から収集",
  },
  {
    id: "disaster-prevention-facility-status",
    category: "災害",
    itemName: "防災施設の位置及び整備の状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "地域防災計画、消防関係資料等の庁内資料から作成",
  },

  // ── その他（景観・歴史資源等） ──────────────────────
  {
    id: "tourism-status",
    category: "その他",
    itemName: "観光の状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
  },
  {
    id: "landscape-heritage-status",
    category: "その他",
    itemName: "景観・歴史資源等の状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
  },
  {
    id: "recreation-facility-status",
    category: "その他",
    itemName: "レクリエーション施設の状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "庁内資料、河川水辺の国勢調査結果、公園管理者・河川管理者による既存調査から収集",
  },
  {
    id: "pollution-occurrence-status",
    category: "その他",
    itemName: "公害の発生状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
  },
];

export const categories = Array.from(new Set(catalog.map((item) => item.category)));

export function itemsByCategory(category: string): CatalogItem[] {
  return catalog.filter((item) => item.category === category);
}
