// 「まちづくりと統計」書籍の表1〜3（都市計画基礎調査のデータ項目、人口・経済に関する基本統計、
// 交通/地価/自然的環境/災害/その他）を1つの配列に構造化したもの。
// UIのカテゴリツリーとダウンロード処理の両方がこの配列を単一情報源として参照する。

export type ApiProvider = "estat" | "reinfolib" | null;

export interface CatalogItem {
  id: string;
  category: string;
  subcategory?: string;
  itemName: string;
  publisher: string;
  frequency: string;
  apiProvider: ApiProvider;
  /** MVPで実際にダウンロード可能なら true。false は「データなし・情報源のみ」表示 */
  apiAvailable: boolean;
  /** e-Stat 統計調査コード（STAT_NAME @code）。getStatsListの絞り込みに使う */
  estatStatsCode?: string;
  /** 統計表タイトルをさらに絞り込むキーワード（部分一致） */
  estatTitleKeyword?: string;
  /** 不動産情報ライブラリ（XPT002）の地価情報区分。0=地価公示のみ, 1=都道府県地価調査のみ */
  reinfolibPriceClassification?: "0" | "1";
  /** 不動産情報ライブラリのXKT/XGT系GISレイヤーAPIコード（区域区分・災害危険区域・学校等） */
  reinfolibGisEndpoint?: string;
  sourceUrl?: string;
  note?: string;
}

export const catalog: CatalogItem[] = [
  // ── 人口 ────────────────────────────────────────────
  {
    id: "population-census",
    category: "人口",
    subcategory: "人口規模・増減・昼間人口・通勤通学移動",
    itemName: "国勢調査",
    publisher: "総務省",
    frequency: "5年ごと",
    apiProvider: "estat",
    apiAvailable: true,
    estatStatsCode: "00200521",
    estatTitleKeyword: "男女別人口",
    sourceUrl: "https://www.e-stat.go.jp/",
    note: "人口規模・人口増減・昼間人口・通勤通学移動・住宅の所有関係別/建て方別世帯数・産業/職業分類別就業者数の元データ",
  },
  {
    id: "vital-statistics",
    category: "人口",
    subcategory: "将来人口（出生・死亡）",
    itemName: "人口動態調査",
    publisher: "厚生労働省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
    sourceUrl: "https://www.e-stat.go.jp/",
    note: "統計調査コード00450011。COLLECT_AREA上は市区町村表が存在するが、実データで検証したところ小規模市町村では値が返らない表が多く、信頼できる絞り込みキーワードを確定できなかったため見送り",
  },
  {
    id: "resident-registry-migration",
    category: "人口",
    subcategory: "将来人口（転入・転出）",
    itemName: "住民基本台帳人口移動報告",
    publisher: "総務省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
    sourceUrl: "https://www.e-stat.go.jp/",
    note: "統計調査コード00200523。e-Stat上の表はすべてCOLLECT_AREA「該当なし」で、市区町村・都道府県単位のデータが存在しないため対象外（実データで確認済み）",
  },
  {
    id: "population-projection",
    category: "人口",
    subcategory: "将来推計人口・世帯数・DID",
    itemName: "日本の地域別将来推計人口",
    publisher: "国立社会保障・人口問題研究所",
    frequency: "概ね5年ごと",
    apiProvider: null,
    apiAvailable: false,
    sourceUrl: "https://www.ipss.go.jp/",
    note: "社人研サイトで都道府県・市区町村別に公表。API未整備",
  },

  // ── 産業（企業・産業関連） ──────────────────────────
  {
    id: "economic-census-basic",
    category: "産業",
    subcategory: "事業所数・従業者数",
    itemName: "経済センサス-基礎調査",
    publisher: "総務省・経済産業省",
    frequency: "5年ごと",
    apiProvider: "estat",
    apiAvailable: true,
    estatStatsCode: "00200552",
    estatTitleKeyword: "民営事業所数及び従業者数",
    sourceUrl: "https://www.e-stat.go.jp/",
  },
  {
    id: "economic-census-activity",
    category: "産業",
    subcategory: "事業所数・従業者数・売上金額",
    itemName: "経済センサス-活動調査",
    publisher: "総務省・経済産業省",
    frequency: "年次*",
    apiProvider: "estat",
    apiAvailable: true,
    estatStatsCode: "00200553",
    estatTitleKeyword: "全事業所数",
    sourceUrl: "https://www.e-stat.go.jp/",
    note: "*経済センサス実施年は経済センサスで調査し、製造業分を集計",
  },
  {
    id: "industrial-statistics",
    category: "産業",
    subcategory: "製造業実態",
    itemName: "工業統計調査",
    publisher: "総務省・経済産業省",
    frequency: "年次*",
    apiProvider: "estat",
    apiAvailable: false,
    note: "統計調査コード00550010。市区町村単位の表は2020年分を最後に更新が止まっており（2021年以降は経済センサス-活動調査に統合）、かつ地域が@areaでなく別軸（@cat03）で表現される特殊な構造のため対象外",
  },
  {
    id: "economic-structure-survey",
    category: "産業",
    subcategory: "産業構造実態",
    itemName: "経済構造実態調査",
    publisher: "経済産業省",
    frequency: "年次*",
    apiProvider: "estat",
    apiAvailable: false,
    note: "統計調査コード00200555。市区町村単位の表はあるが、cdAreaで絞り込んでも地域を問わず全件返ってしまう構造（地域が別軸で表現されている）ため、現行の実装方式では正しく取得できず対象外",
  },
  {
    id: "agriculture-forestry-census",
    category: "産業",
    subcategory: "農地転用状況（行政区域全体）",
    itemName: "農林業センサス",
    publisher: "農林水産省",
    frequency: "5年ごと",
    apiProvider: "estat",
    apiAvailable: false,
    note: "統計調査コード00500209。e-Stat上のデータは全国・都道府県単位のみで、市区町村単位の値が存在しないため対象外（実データで確認済み）",
  },
  {
    id: "fishery-census",
    category: "産業",
    itemName: "漁業センサス",
    publisher: "農林水産省",
    frequency: "5年ごと",
    apiProvider: "estat",
    apiAvailable: false,
    note: "統計調査コード00500210。市区町村単位の表は存在するが最新でも2003年で更新が止まっており、内陸市町村では値が存在しないため実用性が低いと判断し見送り",
  },
  {
    id: "commerce-dynamic-statistics",
    category: "産業",
    itemName: "商業動態統計調査",
    publisher: "経済産業省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
    note: "統計調査コード00550030。e-Stat上のデータは全国・都道府県単位のみで、市区町村単位の値が存在しないため対象外（実データで確認済み）",
  },
  {
    id: "mining-industrial-index",
    category: "産業",
    itemName: "鉱工業指数",
    publisher: "経済産業省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
    note: "e-Stat検索で該当統計表が見つからなかったため対象外（実データで確認済み）",
  },
  {
    id: "zoning-status",
    category: "産業",
    subcategory: "区域区分の状況",
    itemName: "都市計画区域・区域区分",
    publisher: "国土交通省（不動産情報ライブラリ）",
    frequency: "-",
    apiProvider: "reinfolib",
    apiAvailable: true,
    reinfolibGisEndpoint: "XKT001",
    sourceUrl: "https://www.reinfolib.mlit.go.jp/",
    note: "都市計画決定GISデータ（XKT001）。庁内資料の代わりに不動産情報ライブラリのGISレイヤーで取得。Cloudflare Workersデプロイ待ちのため未検証",
  },
  {
    id: "use-district",
    category: "産業",
    subcategory: "区域区分の状況",
    itemName: "用途地域",
    publisher: "国土交通省（不動産情報ライブラリ）",
    frequency: "-",
    apiProvider: "reinfolib",
    apiAvailable: true,
    reinfolibGisEndpoint: "XKT002",
    sourceUrl: "https://www.reinfolib.mlit.go.jp/",
    note: "都市計画決定GISデータ（用途地域, XKT002）。Cloudflare Workersデプロイ待ちのため未検証",
  },

  // ── 家計・労働 ──────────────────────────────────────
  {
    id: "household-survey",
    category: "家計・労働",
    itemName: "家計調査",
    publisher: "総務省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
    note: "統計調査コード00200561。e-Stat上の表はすべてCOLLECT_AREA「該当なし」で、地域別の値が存在しないため対象外（実データで確認済み）",
  },
  {
    id: "national-survey-family-income",
    category: "家計・労働",
    itemName: "消費実態調査（全国家計構造調査）",
    publisher: "総務省",
    frequency: "5年ごと",
    apiProvider: "estat",
    apiAvailable: false,
    note: "統計調査コード00200564。e-Stat上のデータは全国・都道府県単位のみで、市区町村単位の値が存在しないため対象外（実データで確認済み）",
  },
  {
    id: "employment-status-survey",
    category: "家計・労働",
    itemName: "就業構造基本調査",
    publisher: "総務省",
    frequency: "5年ごと",
    apiProvider: "estat",
    apiAvailable: false,
    note: "統計調査コード00200532。市区町村単位の表はあるが、実際の集計対象は政令指定都市・県庁所在都市・人口30万人以上の市に限られ、佐久穂町のような小規模市町村は値が存在しないことを実データで確認",
  },
  {
    id: "wage-structure-survey",
    category: "家計・労働",
    itemName: "賃金構造基本統計調査",
    publisher: "厚生労働省",
    frequency: "年次",
    apiProvider: "estat",
    apiAvailable: false,
    note: "統計調査コード00450091。e-Stat上のデータは全国・都道府県単位のみで、市区町村単位の値が存在しないため対象外（実データで確認済み）",
  },
  {
    id: "labour-force-survey",
    category: "家計・労働",
    itemName: "労働力調査",
    publisher: "総務省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
    sourceUrl: "https://www.e-stat.go.jp/",
    note: "e-Stat上のデータは全国集計のみで、都道府県・市区町村単位の値が存在しないため対象外（実データで確認済み）",
  },
  {
    id: "employment-security-statistics",
    category: "家計・労働",
    itemName: "職業安定業務統計",
    publisher: "厚生労働省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
    note: "e-Stat検索で該当統計表が見つからなかったため対象外（実データで確認済み）",
  },
  {
    id: "monthly-labour-survey",
    category: "家計・労働",
    itemName: "毎月勤労統計",
    publisher: "厚生労働省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
    note: "統計調査コード00450071。e-Stat上の表はすべてCOLLECT_AREA「該当なし」で、地域別の値が存在しないため対象外（実データで確認済み）",
  },

  // ── 物価・地価 ──────────────────────────────────────
  {
    id: "retail-price-survey-structure",
    category: "物価・地価",
    itemName: "小売物価統計調査（構造編）",
    publisher: "総務省",
    frequency: "年次",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "retail-price-survey-trend",
    category: "物価・地価",
    itemName: "小売物価統計調査（動向編）",
    publisher: "総務省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
  },
  {
    id: "consumer-price-index",
    category: "物価・地価",
    itemName: "消費者物価指数",
    publisher: "総務省",
    frequency: "月次",
    apiProvider: "estat",
    apiAvailable: false,
    sourceUrl: "https://www.e-stat.go.jp/",
    note: "e-Stat上の統計表は地域コードでの取得に対応しておらず（都道府県庁所在市及び人口15万人以上の市のみが表内の列として存在）、市区町村コードでの一括取得はできないため対象外（実データで確認済み）",
  },
  {
    id: "cpi-regional-difference",
    category: "物価・地価",
    itemName: "消費者物価地域差指数",
    publisher: "総務省",
    frequency: "年次",
    apiProvider: "estat",
    apiAvailable: false,
    note: "消費者物価指数と同様、都道府県庁所在市等の代表都市のみが対象で市区町村コードでの一括取得ができないため対象外",
  },
  {
    id: "land-price-publication",
    category: "物価・地価",
    itemName: "地価公示",
    publisher: "国土交通省",
    frequency: "半年",
    apiProvider: "reinfolib",
    apiAvailable: true,
    reinfolibPriceClassification: "0",
    sourceUrl: "https://www.reinfolib.mlit.go.jp/",
  },
  {
    id: "prefectural-land-price-survey",
    category: "物価・地価",
    itemName: "都道府県地価調査（基準地価）",
    publisher: "都道府県",
    frequency: "半年",
    apiProvider: "reinfolib",
    apiAvailable: true,
    reinfolibPriceClassification: "1",
    sourceUrl: "https://www.reinfolib.mlit.go.jp/",
  },
  {
    id: "roadside-land-price",
    category: "物価・地価",
    itemName: "路線価",
    publisher: "国税庁",
    frequency: "年次",
    apiProvider: null,
    apiAvailable: false,
    sourceUrl: "https://www.rosenka.nta.go.jp/",
    note: "国税庁の財産評価基準書（路線価図）。公式APIなし",
  },

  // ── 県民経済計算 ────────────────────────────────────
  {
    id: "prefectural-accounts",
    category: "県民経済計算",
    itemName: "県民経済計算・県内総生産・県民所得",
    publisher: "都道府県",
    frequency: "年次",
    apiProvider: null,
    apiAvailable: false,
    note: "都道府県ごとに個別公開されており統一APIなし",
  },
  {
    id: "municipal-accounts",
    category: "県民経済計算",
    itemName: "市内総生産・市民所得",
    publisher: "市",
    frequency: "年次",
    apiProvider: null,
    apiAvailable: false,
    note: "市ごとに個別公開されており統一APIなし",
  },
  {
    id: "input-output-table",
    category: "県民経済計算",
    itemName: "産業連関表・延長産業連関表",
    publisher: "市・総務省",
    frequency: "年次 / 5年ごと",
    apiProvider: "estat",
    apiAvailable: false,
    note: "統計調査コード00200603。e-Stat上の表はすべてCOLLECT_AREA「該当なし」で、地域別の値が存在しないため対象外（実データで確認済み）",
  },

  // ── 土地利用 ────────────────────────────────────────
  {
    id: "land-use-status",
    category: "土地利用",
    itemName: "土地利用現況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "現地調査、空中写真、固定資産課税台帳、登記簿、住宅地図等より収集",
  },
  {
    id: "public-land-status",
    category: "土地利用",
    itemName: "国公有地の状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "登記簿、庁内資料から収集",
  },
  {
    id: "residential-development-status",
    category: "土地利用",
    itemName: "宅地開発状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "市街地開発事業等は都市計画図書等、開発許可による開発は開発登録簿から収集",
  },
  {
    id: "farmland-conversion-status",
    category: "土地利用",
    itemName: "農地転用状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "農地転用申請書から収集。面積は都市計画区域内は土地利用現況、行政区域全体は農林業センサスより収集",
  },
  {
    id: "forest-land-conversion-status",
    category: "土地利用",
    itemName: "林地転用状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "地域森林計画対象民有林は林地開発許可申請、保安林は保安林指定（解除）申請書から収集",
  },
  {
    id: "new-construction-trend",
    category: "土地利用",
    itemName: "新築動向",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "建築確認申請、登記簿（固定資産台帳）から収集",
  },
  {
    id: "ordinance-agreement-status",
    category: "土地利用",
    itemName: "条例・協定",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
  },
  {
    id: "agri-forestry-fishery-policy-status",
    category: "土地利用",
    itemName: "農林漁業関係施策適用状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
  },

  // ── 建物 ────────────────────────────────────────────
  {
    id: "building-use-status",
    category: "建物",
    itemName: "建物利用現況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "現地調査、空中写真、固定資産台帳、登記簿、建築確認申請、住宅地図等から収集",
  },
  {
    id: "large-retail-store-status",
    category: "建物",
    itemName: "大規模小売店舗等の立地状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "法律に基づく届出資料等から収集",
  },
  {
    id: "housing-tenure-type",
    category: "建物",
    itemName: "住宅の所有関係別・建て方別世帯数",
    publisher: "総務省",
    frequency: "5年ごと",
    apiProvider: "estat",
    apiAvailable: false,
    note: "国勢調査に含まれる",
  },

  // ── 都市施設 ────────────────────────────────────────
  {
    id: "urban-facility-status",
    category: "都市施設",
    itemName: "都市施設の位置・内容等",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "都市計画図書、都市計画総括図（都市施設）、庁内資料等から収集。個別施設は下記の学校・医療機関等の不動産情報ライブラリAPIで代替可能",
  },
  {
    id: "school-facility",
    category: "都市施設",
    itemName: "学校",
    publisher: "国土交通省（不動産情報ライブラリ）",
    frequency: "-",
    apiProvider: "reinfolib",
    apiAvailable: true,
    reinfolibGisEndpoint: "XKT006",
    sourceUrl: "https://www.reinfolib.mlit.go.jp/",
    note: "学校API（XKT006）。Cloudflare Workersデプロイ待ちのため未検証",
  },
  {
    id: "medical-facility",
    category: "都市施設",
    itemName: "医療機関",
    publisher: "国土交通省（不動産情報ライブラリ）",
    frequency: "-",
    apiProvider: "reinfolib",
    apiAvailable: true,
    reinfolibGisEndpoint: "XKT010",
    sourceUrl: "https://www.reinfolib.mlit.go.jp/",
    note: "医療機関API（XKT010）。Cloudflare Workersデプロイ待ちのため未検証",
  },
  {
    id: "road-status",
    category: "都市施設",
    itemName: "都市計画道路",
    publisher: "国土交通省（不動産情報ライブラリ）",
    frequency: "-",
    apiProvider: "reinfolib",
    apiAvailable: true,
    reinfolibGisEndpoint: "XKT030",
    sourceUrl: "https://www.reinfolib.mlit.go.jp/",
    note: "都市計画決定GISデータ（都市計画道路, XKT030）。一般道路網全体ではなく都市計画道路のみが対象。Cloudflare Workersデプロイ待ちのため未検証",
  },

  // ── 交通 ────────────────────────────────────────────
  {
    id: "traffic-volume",
    category: "交通",
    itemName: "主要な幹線の断面交通量・混雑度・旅行速度",
    publisher: "国土交通省",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "全国道路交通・街路情勢調査（一般交通量調査）報告書から収集",
  },
  {
    id: "vehicle-od-flow",
    category: "交通",
    itemName: "自動車流動量",
    publisher: "国土交通省",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "全国道路交通・街路情勢調査（自動車起終点調査）報告書から収集",
  },
  {
    id: "rail-tram-status",
    category: "交通",
    itemName: "鉄道・路面電車等の状況",
    publisher: "各交通事業者",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "各交通事業者資料、大都市交通センサス（三大都市圏のみ）、都市交通年報（三大都市圏のみ）から収集",
  },
  {
    id: "bus-status",
    category: "交通",
    itemName: "バスの状況",
    publisher: "各交通事業者",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "乗降客数は一般乗合旅客自動車運送事業輸送実績報告書から収集。GTFS-JPでオープンデータ公開している自治体はそのデータが活用可能",
  },

  // ── 自然的環境 ──────────────────────────────────────
  {
    id: "terrain-hydrology-geology",
    category: "自然的環境",
    itemName: "地形・水系・地質条件",
    publisher: "国土地理院・国土交通省",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "土地条件図・治水地形分類図（国土地理院）、主要水系調査（不動産・建設経済局）、土地分類基本調査（国土政策局）等をもとに整理",
  },
  {
    id: "weather-status",
    category: "自然的環境",
    itemName: "気象状況",
    publisher: "気象庁",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "気象庁の観測データ、大気汚染常時監視測定局の測定データ等から収集。観測地点ベースで市区町村と単純対応しないため対象外",
  },
  {
    id: "greenery-status",
    category: "自然的環境",
    itemName: "緑の状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "航空写真、衛星画像、土地利用現況調査より収集・作成",
  },
  {
    id: "flora-fauna-survey",
    category: "自然的環境",
    itemName: "動植物調査",
    publisher: "環境省・都道府県・市町村",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "自然環境保全基礎調査、河川水辺の国勢調査、環境省レッドデータブック、都道府県又は市町村による既存調査、庁内資料等から収集",
  },

  // ── 災害 ────────────────────────────────────────────
  {
    id: "disaster-occurrence-status",
    category: "災害",
    itemName: "災害の発生状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "既往災害は庁内資料から収集。災害リスク情報（ハザード区域）は下記の各種GISレイヤーAPIで代替可能",
  },
  {
    id: "landslide-hazard-area",
    category: "災害",
    itemName: "土砂災害警戒区域",
    publisher: "国土交通省（不動産情報ライブラリ）",
    frequency: "-",
    apiProvider: "reinfolib",
    apiAvailable: true,
    reinfolibGisEndpoint: "XKT029",
    sourceUrl: "https://www.reinfolib.mlit.go.jp/",
    note: "土砂災害警戒区域API（XKT029）。Cloudflare Workersデプロイ待ちのため未検証",
  },
  {
    id: "flood-hazard-area",
    category: "災害",
    itemName: "洪水浸水想定区域",
    publisher: "国土交通省（不動産情報ライブラリ）",
    frequency: "-",
    apiProvider: "reinfolib",
    apiAvailable: true,
    reinfolibGisEndpoint: "XKT026",
    sourceUrl: "https://www.reinfolib.mlit.go.jp/",
    note: "洪水浸水想定区域（想定最大規模）API（XKT026）。Cloudflare Workersデプロイ待ちのため未検証",
  },
  {
    id: "disaster-prevention-facility-status",
    category: "災害",
    itemName: "指定緊急避難場所",
    publisher: "国土交通省（不動産情報ライブラリ）",
    frequency: "-",
    apiProvider: "reinfolib",
    apiAvailable: true,
    reinfolibGisEndpoint: "XGT001",
    sourceUrl: "https://www.reinfolib.mlit.go.jp/",
    note: "指定緊急避難場所API（XGT001）。庁内資料の代わりに不動産情報ライブラリのGISレイヤーで取得。Cloudflare Workersデプロイ待ちのため未検証",
  },

  // ── その他（景観・歴史資源等） ──────────────────────
  {
    id: "tourism-status",
    category: "その他",
    itemName: "観光の状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
  },
  {
    id: "landscape-heritage-status",
    category: "その他",
    itemName: "景観・歴史資源等の状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
  },
  {
    id: "recreation-facility-status",
    category: "その他",
    itemName: "レクリエーション施設の状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
    note: "庁内資料、河川水辺の国勢調査結果、公園管理者・河川管理者による既存調査から収集",
  },
  {
    id: "pollution-occurrence-status",
    category: "その他",
    itemName: "公害の発生状況",
    publisher: "都道府県・市町村（庁内資料）",
    frequency: "-",
    apiProvider: null,
    apiAvailable: false,
  },
];

export const categories = Array.from(new Set(catalog.map((item) => item.category)));

export function itemsByCategory(category: string): CatalogItem[] {
  return catalog.filter((item) => item.category === category);
}
